
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
idol_card = {suit = 'Spades', rank = 'Ace'},
mail_card = {rank = 'Ace'},
ancient_card = {suit = 'Spades'},
'''
position = 'after'
payload = '''
young_card = {suit = 'Spades'},
old_card = {suit = 'Spades'},
saturated_card = {suit = 'Spades'},
'''
match_indent = true

# SMODS.change_booster_limit
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''G.GAME.modifiers.extra_boosters = (G.GAME.modifiers.extra_boosters or 0) + mod'''
position = "after"
payload = '''
if mod < 0 and G.shop then
    --Remove a booster pack if there's too much in shop
    if #G.shop_booster.cards > G.shop_booster.config.card_limit then 
        G.shop_booster.cards[#G.shop_booster.cards]:remove()
        G.shop_booster.config.card_limit = math.max(G.shop_booster.config.card_limit + mod,2)
    end
end
'''
match_indent = true

# SMODS.change_voucher_limit
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''G.GAME.modifiers.extra_vouchers = (G.GAME.modifiers.extra_vouchers or 0) + mod'''
position = "after"
payload = '''
if mod < 0 and G.shop then
    --Remove a voucher if there's too much in shop

    if #G.shop_vouchers.cards > G.shop_vouchers.config.card_limit + mod then 
        G.shop_vouchers.cards[#G.shop_vouchers.cards]:remove()
    end

    -- Also remove from the spawn list
    if G.GAME.current_round.voucher and #G.GAME.current_round.voucher > 0 then
        local last_voucher = G.GAME.current_round.voucher[#G.GAME.current_round.voucher]
        G.GAME.current_round.voucher.spawn[last_voucher] = false
        table.remove(G.GAME.current_round.voucher, #G.GAME.current_round.voucher)
    end
    
end
'''
match_indent = true


# Wild 4 Card -- 1% chance of appearing
[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''        if (_type == 'Planet' or _type == 'Spectral') and
        not (G.GAME.used_jokers['c_black_hole'] and not SMODS.showman('c_black_hole')) then
            if pseudorandom('soul_'.._type..G.GAME.round_resets.ante) > 0.997 then
                forced_key = 'c_black_hole'
            end
        end'''
position = "after"
payload = '''
if _type == 'Uno' and
not (G.GAME.used_jokers['c_whiteem_wild4'] and not SMODS.showman('c_whiteem_wild4')) then
    if pseudorandom('soul_'.._type..G.GAME.round_resets.ante) > 0.99 then
        forced_key = 'c_whiteem_wild4'
    end
end
'''
match_indent = true